spring:
  jpa:
    database: mysql
  application:
    name: sss
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8087
logging:
  file:
    name: test.log
  level:
    com: info
my:
  xiaobaishu:
    id: 13
    msg:  我是天才

